name: Go CI

on:
  push:
    branches: ["main"]
    paths:
      - glide-core/**
      - submodules/**
      - go/**
      - .github/workflows/go.yml
  pull_request:
    paths:
      - glide-core/**
      - submodules/**
      - go/**
      - .github/workflows/go.yml

# Run only the latest job on a branch and cancel previous ones
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-go-client:
    timeout-minutes: 25
    strategy:
      # Run all jobs
      fail-fast: false
      matrix:
        go:
#          - '1.18'
          - '1.21'
        redis:
#          - 6.2.14
          - 7.2.3
        os:
          - ubuntu-latest
#          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1'

      - name: Install shared software dependencies
        uses: ./.github/workflows/install-shared-dependencies
        with:
          os: ${{ matrix.os }}
          target: ${{ matrix.os == 'ubuntu-latest' && 'x86_64-unknown-linux-gnu' || 'x86_64-apple-darwin' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install redis
        # TODO: make this step macos compatible: https://github.com/aws/glide-for-redis/issues/781
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: ./.github/workflows/install-redis
        with:
          redis-version: ${{ matrix.redis }}

      - name: Install client dependencies
        working-directory: ./go
        run: make install-dependencies

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Build client
        working-directory: ./go
        run: |
          go mod edit -go=${{ matrix.go }}
          make build

      - name: Run go vet linter
        working-directory: ./go
        run: go vet .

      - name: Run staticcheck linter
        working-directory: ./go
        run: go staticcheck .

      - name: Run unit tests
        working-directory: ./go
        run: make unit-test-report

      - name: Upload test reports
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-go-${{ matrix.go }}-redis-${{ matrix.redis }}-${{ matrix.os }}
          path: |
            go/reports/unit-test-report.html

  lint-rust:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/workflows/lint-rust
        with:
          cargo-toml-folder: ./go
        name: lint go rust
