name: SQL Java CI

on:
  pull_request:
  push:
    paths:
      - "java/**"
      - ".github/workflows/java.yml"

# Run only most latest job on a branch and cancel previous ones
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      # Run all jobs
      fail-fast: false
      matrix:
        java:
          - 11
          - 17
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}

      - name: Install and run protoc (protobuf)
        run: |
          sudo apt update
          sudo apt install protobuf-compiler
          protoc -Iprotobuf=babushka-core/src/protobuf/ --java_out=java/jabushka/jabushka babushka-core/src/protobuf/*.proto

      - name: Build rust part
        working-directory: java
        run: cargo build

      - name: Build with Gradle
        working-directory: java/jabushka
        run: ./gradlew --continue build

      - name: Upload test reports
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: test-reports-${{ matrix.java }}
          path: |
            java/jabushka/jabushka/build/**
            java/jabushka/integTest/build/**
