name: Java client benchmarks

on:
  workflow_dispatch:
    inputs:
      name:
        required: false
        type: string

run-name: ${{ inputs.name == '' && format('{0} @ {1}', github.ref_name, github.sha) || inputs.name }}

jobs:
  build:
    strategy:
      matrix:
        java:
          - 11
          - 17
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}

      # TODO: uncomment once benchmark implemented
      # - name: Run benchmarks
      #  working-directory: java/jabushka
      #  run: ./gradlew -Pbenchmark :benchmark:jedis :benchmark:lettuce :benchmark:jabushka

      - name: Upload test reports
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: test-reports-${{ matrix.java }}
          path: |
            java/jabushka/benchmarks/build/**
